### ISSUE TITLE
Expand Answer for Conditional Responses get Stuck

### ISSUE THREAD

**Issue by solo16** [cabarius/ToyBox#893]
Hi,
Just like to report there is minor issue on such function. When it is on the "I Have to go" dialog option isn't clickable.
![dialog](https://github.com/cabarius/ToyBox/assets/90235244/d6611141-2bf2-489b-a3b4-3bf25ec67b49)
I need to turn it off in order to proceed the dialog.

![normal dialog](https://github.com/cabarius/ToyBox/assets/90235244/fb732d1e-4e7f-4bc2-840f-dd8928bf917f)

FYI, I'm currently playing the DLC Inevitable Excess. 

Thank you for looking into this!

**Comment by solo16** [comment]
Yes but my save file isn't "clean" I got save dependent mod like Champion feat Anew.  Anyway here are my mod lists:
Champion Feats Anew 1.0.16
Custom NPC Portraits 1.1.2
No Film Grain 1.0
Path of Bling 1.0.5
ToyBox 1.5.1e
Weapon Focus Plus 1.2.3


Thank you so much for your time and efforts!!!

[Manual_1187_bug_test_save.zip](https://github.com/cabarius/ToyBox/files/11463134/Manual_1187_bug_test_save.zip)

**Comment by cabarius** [comment]
How far into the DLC is it?

**Comment by solo16** [comment]
Just start haven't start any quest yet. Like just went out from the starting point to the camp about like 5mins or so.

Thank you!

**Comment by cabarius** [comment]
Fixed in 1.5.2.  You can try it out in the Preview on the discord.

**Comment by solo16** [comment]
Hi,

I have tried the latest preview version from the discord and tested again, sadly the issue is still there I couldn't click on the I have to go dialog option unless I turn off the function.

Sorry to reopen the issue again!

Thank you so much!

**Comment by solo16** [comment]
Game ver. 2.1.3j
ToyBox 1.5.1i

Thanks!

**Comment by CasDragon** [comment]
Is this still an issue, or is this fixed?

**Comment by CasDragon** [comment]
Closing due to inactivity
